- name: pull values from parameter store
  become: yes
  connection: ssh
  hosts: all
  tasks:
    - name: Create or update key/value pair in AWS SSM parameter store
      community.aws.ssm_parameter:
        name: "{{item.name}}"
        description: "auto creating parameters through ansible"
        value: "{{item.value}}"
        region: us-east-1
      loop:
          - { name: "dev.cart.REDIS_HOST", value: "redis-dev.devops007.online" }
          - { name: "dev.cart.CATALOGUE_HOST", value: "catalogue-dev.devops007.online" }
          - { name: "dev.catalogue.MONGO", value: "true" }
          - { name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.devops007.online:27017/catalogue" }
          - { name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.devops007.online:27017/catalogue" }
          - { name: "dev.frontend.CATALOGUE_URL", value: "http://catalogue-dev.devops007.online:80/" }
          - { name: "dev.frontend.CART_URL", value: "http://cart-dev.devops007.online:80/" }
          - { name: "dev.frontend.USER_URL", value: "http://user-dev.devops007.online:80/" }
          - { name: "dev.frontend.PAYMENT_URL", value: "http://payment-dev.devops007.online:80/" }
          - { name: "dev.frontend.SHIPPING_URL", value: "http://shipping-dev.devops007.online:80/" }
          - { name: "dev.payment.CART_HOST", value: "cart-dev.devops007.online" }
          - { name: "dev.payment.USER_HOST", value: "user-dev.devops007.online" }
          - { name: "dev.payment.CART_PORT", value: "80" }
          - { name: "dev.payment.USER_PORT", value: "80" }
          - { name: "dev.payment.AMQP_HOST", value: "rabbitmq-dev.devops007.online" }
          - { name: "dev.payment.AMQP_USER", value: "roboshop" }
          - { name: "dev.shipping.CART_ENDPOINT", value: "cart-dev.devops007.online:80" }
          - { name: "dev.shipping.DB_HOST", value: "mysql-dev.devops007.online" }
          - { name: "dev.user.MONGO", value: "true" }
          - { name: "dev.user.MONGO_URL", value: "mongodb://mongodb-dev.devops007.online:27017/users" }
          - { name: "dev.user.REDIS_HOST", value: "redis-dev.devops007.online" }
