- name: pull values from parameter store
  become: yes
  connection: ssh
  hosts: all
  tasks:
    - name: lookup ssm parameter store in specified region
      debug: msg="{{ lookup('amazon.aws.aws_ssm', 'test') }}"
