#    - name: install nginx
#      ansible.builtin.yum:
#        name: nginx
#        state: installed
#
#    - name: start nginx
#      ansible.builtin.systemd:
#        name: nginx
#        state: started

- name: hellowrold
  ansible.builtin.debug:
    msg: hello world