- name: disable mysqld
  ansible.builtin.shell: dnf module disable mysql -y

- name: copy mysqld conf file
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysqld
  ansible.builtin.yum:
    name: mysql-community-server -y
    state: present

- name: start mysql
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: set mysql root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{mysql_root_password}}
  ignore_errors: yes


