- name: copy mongodb conf file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/systemd/system/mongodb.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell -y

- name: load schema
  community.mongodb.mongodb_shell:
    file: "/app/schema/{{component}}.js"
    idempotent: true
    login_host: mongod-dev.devops007.online