- name: copy mongodb conf file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load schema
  community.mongodb.shell: mongo --ssl --host mongod-dev.devops007.online </app/schema/catalogue.js
#    file: "/app/schema/{{component}}.js"
#    idempotent: true
#    login_host: mongod-dev.devops007.online