- name: load mysql schema
  community.mysql.mysql_db:
    login_host: mysql-dev.devops007.online
    login_user: root
    login_password: "{{mysql_password}}"
    name: mysql
    state: present
    target: /app/schema/{{component}}.sql

- name: Install Python Deps
  ansible.builtin.yum:
    name:
      - python3-PyMySQL
      - mysql
    state: installed
