- name: copy systemd file
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service
#    remote_src: yes

- name: start service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

#      - name: COpy SystemD file
#        ansible.builtin.template:
#          src: "{{component}}.service"
#          dest: /etc/systemd/system/{{component}}.service
#
#      - name: Start {{component}} Service
#        ansible.builtin.systemd:
#          name: "{{component}}"
#          daemon_reload: yes
#          enabled: yes
#          state: restarted